name: Publish release to PyPi

on:
  push:
    tags:
      - "v[0-9]+_[0-9]+_[0-9]+"

jobs:
  pypi-publish:
    name: Publish
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    environment: release

    permissions:
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: "1.7.1"

      - name: Build distribution
        run: poetry build

      - name: Store distribution package
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
